import { Box, Typography, useTheme } from "@mui/material"
import { DataGrid } from "@mui/x-data-grid"
import { tokens } from "../../theme"
import { mockDataTeam } from "../../data/mock-data"
import AdminPanelSettingsOutlinedIcon from "@mui/icons-material"